function runSampling(batch,n1,n2);
% Function to call sampling. The file samples.mat is generated by the user
% and is a Nxn matrix, with N the number of sample sets and n the number of
% parameters. It is recommended to make samples.mat with Latin Hypercube
% Sampling with the script lhsu.m from Budiman Minasny (2004,
% budiman@acss.usyd.edu.au). This file can be downloaded from
% http://www.mathworks.com/matlabcentral/fileexchange/4352-latin-hypercube-sampling/content/lhsu.m

load samples.mat

[parD,parS,parT,parR,parSig,parNo]=sampleOscillationsOligator(samples,-1,1,0,2,0,2,0,2,5,12,n1,n2);
eval(['save parD',num2str(batch),'.dat parD /ascii'])
eval(['save parS',num2str(batch),'.dat parS /ascii'])
eval(['save parT',num2str(batch),'.dat parT /ascii'])
eval(['save parR',num2str(batch),'.dat parR /ascii'])
eval(['save parSig',num2str(batch),'.dat parSig /ascii'])
eval(['save parNo',num2str(batch),'.dat parNo /ascii'])
%
% Rik van Roekel, 2014
%
% Licensing:
%   Copyright (C) 2011-2015 Rik van Roekel. All rights
%   reserved.
%
%   Contact: rikvanroekel@gmail.com
%
%   This file is part of the Automated DNA Design Software (ADDS).
%   
%   ADDS is free software: you can redistribute it 
%   and/or modify it under the terms of the GNU General 
%   Public License as published by the Free Software 
%   Foundation, either version 3 of the License, or (at 
%   your option) any later version.
%
%   ADDS is distributed in the hope that it will be
%   useful, but WITHOUT ANY WARRANTY; without even the 
%   implied warranty of MERCHANTABILITY or FITNESS FOR A 
%   PARTICULAR PURPOSE.  See the GNU General Public 
%   License for more details (http://www.gnu.org/licenses/).