function runSampling(batch,n1,n2);
% Function to call sampling. The file samples.mat is generated by the user
% and is a Nxn matrix, with N the number of sample sets and n the number of
% parameters. It is recommended to make samples.mat with Latin Hypercube
% Sampling with the script lhsu.m from Budiman Minasny (2004,
% budiman@acss.usyd.edu.au). This file can be downloaded from
% http://www.mathworks.com/matlabcentral/fileexchange/4352-latin-hypercube-sampling/content/lhsu.m

load samples

[parg,SPg,parb,SPb,parNo]=samplePIFFLFull(samples,-1,2,-1,2,-1,2,-1,2,5,12,1,2,n1,n2);
eval(['save parg',num2str(batch),'.dat parg /ascii'])
eval(['save SPg',num2str(batch),'.dat SPg /ascii'])
eval(['save parb',num2str(batch),'.dat parb /ascii'])
eval(['save SPb',num2str(batch),'.dat SPb /ascii'])
eval(['save parNo',num2str(batch),'.dat parNo /ascii'])
%
% Rik van Roekel, 2014
%
% Licensing:
%   Copyright (C) 2011-2015 Rik van Roekel. All rights
%   reserved.
%
%   Contact: rikvanroekel@gmail.com
%
%   This file is part of the Automated DNA Design Software (ADDS).
%   
%   ADDS is free software: you can redistribute it 
%   and/or modify it under the terms of the GNU General 
%   Public License as published by the Free Software 
%   Foundation, either version 3 of the License, or (at 
%   your option) any later version.
%
%   ADDS is distributed in the hope that it will be
%   useful, but WITHOUT ANY WARRANTY; without even the 
%   implied warranty of MERCHANTABILITY or FITNESS FOR A 
%   PARTICULAR PURPOSE.  See the GNU General Public 
%   License for more details (http://www.gnu.org/licenses/).